apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-sh
data:
  import.sh: |
    #!/bin/bash
    echo "--- AUTOMATIKUS IMPORT INDÍTÁSA ---"
    mongoimport --db lpdb --collection albums --file /data/init/albums.json --jsonArray
    echo "--- IMPORT KÉSZ ---"
